from sqlalchemy import Column, Integer, String, Float, Boolean
from bd.database import BaseGold

class Cliente360(BaseGold):
    __tablename__ = "dm_cliente_360"

    id_cliente = Column(String, primary_key=True, index=True)
    nome_cliente = Column(String)
    sobrenome_cliente = Column(String)
    nome_completo_cliente = Column(String, index=True)
    email_cliente = Column(String)
    telefone_cliente = Column(String)
    genero_cliente = Column(String)
    cidade_cliente = Column(String)
    estado_cliente = Column(String)
    pais_cliente = Column(String)
    origem_cliente = Column(String)
    data_cadastro_cliente = Column(String)
    idade_cliente = Column(Integer)
    total_pedidos = Column(Integer)
    receita_total_cliente = Column(Float)
    ticket_medio_cliente = Column(Float)
    total_itens_comprados = Column(Integer)
    data_primeira_compra = Column(String)
    data_ultima_compra = Column(String)
    recencia_dias = Column(Integer)
    pedidos_aprovados = Column(Integer)
    pedidos_recusados = Column(Integer)
    pedidos_processando = Column(Integer)
    pedidos_reembolsados = Column(Integer)
    total_tickets = Column(Integer)
    tickets_abertos = Column(Integer)
    tickets_fechados = Column(Integer)
    tempo_medio_resolucao_horas = Column(Float)
    nota_media_atendimento = Column(Float)
    data_ultimo_ticket = Column(String)
    total_avaliacoes = Column(Integer)
    nota_media_produto = Column(Float)
    nps_medio_cliente = Column(Float)
    taxa_recomendacao_cliente = Column(Float)
    data_ultima_avaliacao = Column(String)
    total_sessoes = Column(Integer)
    total_eventos = Column(Integer)
    tempo_medio_pagina_seg = Column(Float)
    data_ultimo_evento = Column(String)
    eventos_compra = Column(Integer)
    eventos_add_carrinho = Column(Integer)
    eventos_pageview = Column(Integer)
    faixa_valor_cliente = Column(String)
    cliente_ativo_90d = Column(Boolean)
