from sqlalchemy import Column, Integer, String, Float, Boolean
from bd.database import BaseGold

class Produto360(BaseGold):
    __tablename__ = "dm_produto_360"

    id_produto = Column(String, primary_key=True, index=True)
    nome_produto = Column(String, index=True)
    categoria_produto = Column(String, index=True)
    preco_produto = Column(Float)
    fornecedor_produto = Column(String)
    peso_kg_produto = Column(Float)
    estoque_produto = Column(Integer)
    produto_ativo = Column(Boolean)
    data_cadastro_produto = Column(String)
    faixa_preco_produto = Column(String)
    status_estoque_produto = Column(String)
    total_pedidos = Column(Integer)
    quantidade_vendida = Column(Integer)
    receita_total_produto = Column(Float)
    ticket_medio_produto = Column(Float)
    data_primeira_venda = Column(String)
    data_ultima_venda = Column(String)
    pedidos_aprovados = Column(Integer)
    pedidos_recusados = Column(Integer)
    pedidos_processando = Column(Integer)
    pedidos_reembolsados = Column(Integer)
    total_avaliacoes = Column(Integer)
    nota_media_produto = Column(Float)
    nps_medio_produto = Column(Float)
    taxa_recomendacao_produto = Column(Float)
    data_ultima_avaliacao = Column(String)
    total_tickets_produto = Column(Integer)
    tempo_medio_resolucao_produto = Column(Float)
    total_eventos_produto = Column(Integer)
    total_sessoes_produto = Column(Integer)
    total_pageviews_produto = Column(Integer)
    total_add_carrinho_produto = Column(Integer)
    total_eventos_compra_produto = Column(Integer)
    data_ultimo_evento_produto = Column(String)
    status_comercial_produto = Column(String)
    produto_com_alto_volume_suporte = Column(Boolean)
    ja_tratada = Column(Boolean, default=True)
