"""add_data_cadastro_cliente

Revision ID: 2a594067c87a
Revises: 062526031b3d
Create Date: 2026-05-13 20:57:20.079917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a594067c87a'
down_revision: Union[str, None] = '062526031b3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dim_cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_cadastro_cliente', sa.String(), nullable=True))

    with op.batch_alter_table('fato_suporte', schema=None) as batch_op:
        batch_op.alter_column('data_abertura',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('data_resolucao',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               existing_nullable=True)

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=False))
        batch_op.drop_index('ix_usuarios_username')
        batch_op.create_index(batch_op.f('ix_usuarios_username'), ['username'], unique=False)
        batch_op.create_index(batch_op.f('ix_usuarios_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_email'))
        batch_op.drop_index(batch_op.f('ix_usuarios_username'))
        batch_op.create_index('ix_usuarios_username', ['username'], unique=1)
        batch_op.drop_column('email')

    with op.batch_alter_table('fato_suporte', schema=None) as batch_op:
        batch_op.alter_column('data_resolucao',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.alter_column('data_abertura',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    with op.batch_alter_table('dim_cliente', schema=None) as batch_op:
        batch_op.drop_column('data_cadastro_cliente')

    # ### end Alembic commands ###
