"""initial_migration

Revision ID: 4285b3fda69c
Revises: 
Create Date: 2026-05-07 21:50:06.250123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4285b3fda69c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_cliente',
    sa.Column('id_cliente', sa.String(), nullable=False),
    sa.Column('nome_cliente', sa.String(), nullable=True),
    sa.Column('sobrenome_cliente', sa.String(), nullable=True),
    sa.Column('email_cliente', sa.String(), nullable=True),
    sa.Column('telefone_cliente', sa.String(), nullable=True),
    sa.Column('ramal_cliente', sa.String(), nullable=True),
    sa.Column('genero_cliente', sa.String(), nullable=True),
    sa.Column('endereco_cliente', sa.String(), nullable=True),
    sa.Column('cidade_cliente', sa.String(), nullable=True),
    sa.Column('estado_cliente', sa.String(), nullable=True),
    sa.Column('pais_cliente', sa.String(), nullable=True),
    sa.Column('origem_cliente', sa.String(), nullable=True),
    sa.Column('data_nascimento_cliente', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_cliente')
    )
    with op.batch_alter_table('dim_cliente', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dim_cliente_email_cliente'), ['email_cliente'], unique=False)
        batch_op.create_index(batch_op.f('ix_dim_cliente_nome_cliente'), ['nome_cliente'], unique=False)
        batch_op.create_index(batch_op.f('ix_dim_cliente_sobrenome_cliente'), ['sobrenome_cliente'], unique=False)

    op.create_table('dim_produto',
    sa.Column('id_produto', sa.String(), nullable=False),
    sa.Column('nome_produto', sa.String(), nullable=True),
    sa.Column('categoria_produto', sa.String(), nullable=True),
    sa.Column('preco_produto', sa.Float(), nullable=True),
    sa.Column('fornecedor_produto', sa.String(), nullable=True),
    sa.Column('estoque_produto', sa.Integer(), nullable=True),
    sa.Column('produto_ativo', sa.Boolean(), nullable=True),
    sa.Column('faixa_preco', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_produto')
    )
    with op.batch_alter_table('dim_produto', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dim_produto_categoria_produto'), ['categoria_produto'], unique=False)
        batch_op.create_index(batch_op.f('ix_dim_produto_id_produto'), ['id_produto'], unique=False)
        batch_op.create_index(batch_op.f('ix_dim_produto_nome_produto'), ['nome_produto'], unique=False)

    op.create_table('fato_avaliacoes',
    sa.Column('id_avaliacao', sa.String(), nullable=False),
    sa.Column('id_cliente', sa.String(), nullable=True),
    sa.Column('id_produto', sa.String(), nullable=True),
    sa.Column('id_pedido', sa.String(), nullable=True),
    sa.Column('nota_produto', sa.Float(), nullable=True),
    sa.Column('nota_nps', sa.Float(), nullable=True),
    sa.Column('recomenda_produto', sa.Boolean(), nullable=True),
    sa.Column('data_avaliacao', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_avaliacao')
    )
    with op.batch_alter_table('fato_avaliacoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fato_avaliacoes_id_avaliacao'), ['id_avaliacao'], unique=False)
        batch_op.create_index(batch_op.f('ix_fato_avaliacoes_id_cliente'), ['id_cliente'], unique=False)
        batch_op.create_index(batch_op.f('ix_fato_avaliacoes_id_produto'), ['id_produto'], unique=False)

    op.create_table('fato_suporte',
    sa.Column('ticket_id', sa.String(), nullable=False),
    sa.Column('id_cliente', sa.String(), nullable=True),
    sa.Column('id_pedido', sa.String(), nullable=True),
    sa.Column('tipo_problema', sa.String(), nullable=True),
    sa.Column('data_abertura', sa.String(), nullable=True),
    sa.Column('data_resolucao', sa.String(), nullable=True),
    sa.Column('tempo_resolucao_horas', sa.Float(), nullable=True),
    sa.Column('agente_suporte', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('ticket_id')
    )
    with op.batch_alter_table('fato_suporte', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fato_suporte_id_cliente'), ['id_cliente'], unique=False)
        batch_op.create_index(batch_op.f('ix_fato_suporte_id_pedido'), ['id_pedido'], unique=False)
        batch_op.create_index(batch_op.f('ix_fato_suporte_ticket_id'), ['ticket_id'], unique=False)

    op.create_table('fato_vendas',
    sa.Column('id_pedido', sa.String(), nullable=False),
    sa.Column('data_pedido', sa.Date(), nullable=True),
    sa.Column('id_cliente', sa.String(), nullable=True),
    sa.Column('id_produto', sa.String(), nullable=True),
    sa.Column('quantidade_produto', sa.Integer(), nullable=True),
    sa.Column('valor_pedido', sa.Float(), nullable=True),
    sa.Column('metodo_pagamento', sa.String(), nullable=True),
    sa.Column('status_pedido', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_pedido')
    )
    with op.batch_alter_table('fato_vendas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fato_vendas_id_cliente'), ['id_cliente'], unique=False)
        batch_op.create_index(batch_op.f('ix_fato_vendas_id_pedido'), ['id_pedido'], unique=False)
        batch_op.create_index(batch_op.f('ix_fato_vendas_id_produto'), ['id_produto'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fato_vendas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fato_vendas_id_produto'))
        batch_op.drop_index(batch_op.f('ix_fato_vendas_id_pedido'))
        batch_op.drop_index(batch_op.f('ix_fato_vendas_id_cliente'))

    op.drop_table('fato_vendas')
    with op.batch_alter_table('fato_suporte', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fato_suporte_ticket_id'))
        batch_op.drop_index(batch_op.f('ix_fato_suporte_id_pedido'))
        batch_op.drop_index(batch_op.f('ix_fato_suporte_id_cliente'))

    op.drop_table('fato_suporte')
    with op.batch_alter_table('fato_avaliacoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fato_avaliacoes_id_produto'))
        batch_op.drop_index(batch_op.f('ix_fato_avaliacoes_id_cliente'))
        batch_op.drop_index(batch_op.f('ix_fato_avaliacoes_id_avaliacao'))

    op.drop_table('fato_avaliacoes')
    with op.batch_alter_table('dim_produto', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dim_produto_nome_produto'))
        batch_op.drop_index(batch_op.f('ix_dim_produto_id_produto'))
        batch_op.drop_index(batch_op.f('ix_dim_produto_categoria_produto'))

    op.drop_table('dim_produto')
    with op.batch_alter_table('dim_cliente', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dim_cliente_sobrenome_cliente'))
        batch_op.drop_index(batch_op.f('ix_dim_cliente_nome_cliente'))
        batch_op.drop_index(batch_op.f('ix_dim_cliente_email_cliente'))

    op.drop_table('dim_cliente')
    # ### end Alembic commands ###
