"""Adicionando clickstream e dispositivo

Revision ID: 68f1620e5d1b
Revises: 
Create Date: 2026-05-07 14:47:07.825042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68f1620e5d1b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_cliente',
    sa.Column('id_cliente', sa.String(), nullable=False),
    sa.Column('nome_cliente', sa.String(), nullable=True),
    sa.Column('sobrenome_cliente', sa.String(), nullable=True),
    sa.Column('email_cliente', sa.String(), nullable=True),
    sa.Column('telefone_cliente', sa.String(), nullable=True),
    sa.Column('ramal_cliente', sa.Integer(), nullable=True),
    sa.Column('genero_cliente', sa.String(), nullable=True),
    sa.Column('data_nascimento_cliente', sa.String(), nullable=True),
    sa.Column('data_cadastro_cliente', sa.String(), nullable=True),
    sa.Column('endereco_cliente', sa.String(), nullable=True),
    sa.Column('cidade_cliente', sa.String(), nullable=True),
    sa.Column('estado_cliente', sa.String(), nullable=True),
    sa.Column('pais_cliente', sa.String(), nullable=True),
    sa.Column('origem_cliente', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_cliente')
    )
    op.create_index(op.f('ix_dim_cliente_email_cliente'), 'dim_cliente', ['email_cliente'], unique=False)
    op.create_index(op.f('ix_dim_cliente_id_cliente'), 'dim_cliente', ['id_cliente'], unique=False)
    op.create_index(op.f('ix_dim_cliente_nome_cliente'), 'dim_cliente', ['nome_cliente'], unique=False)
    op.create_index(op.f('ix_dim_cliente_sobrenome_cliente'), 'dim_cliente', ['sobrenome_cliente'], unique=False)
    op.create_table('dim_cliente_dispositivo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_cliente', sa.String(), nullable=True),
    sa.Column('id_dispositivo', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dim_cliente_dispositivo_id_cliente'), 'dim_cliente_dispositivo', ['id_cliente'], unique=False)
    op.create_index(op.f('ix_dim_cliente_dispositivo_id_dispositivo'), 'dim_cliente_dispositivo', ['id_dispositivo'], unique=False)
    op.create_table('dim_produto',
    sa.Column('id_produto', sa.String(), nullable=False),
    sa.Column('nome_produto', sa.String(), nullable=True),
    sa.Column('categoria_produto', sa.String(), nullable=True),
    sa.Column('preco_produto', sa.Float(), nullable=True),
    sa.Column('fornecedor_produto', sa.String(), nullable=True),
    sa.Column('peso_kg_produto', sa.Float(), nullable=True),
    sa.Column('estoque_produto', sa.Integer(), nullable=True),
    sa.Column('produto_ativo', sa.Boolean(), nullable=True),
    sa.Column('data_cadastro_produto', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_produto')
    )
    op.create_index(op.f('ix_dim_produto_categoria_produto'), 'dim_produto', ['categoria_produto'], unique=False)
    op.create_index(op.f('ix_dim_produto_id_produto'), 'dim_produto', ['id_produto'], unique=False)
    op.create_index(op.f('ix_dim_produto_nome_produto'), 'dim_produto', ['nome_produto'], unique=False)
    op.create_table('fato_avaliacoes',
    sa.Column('id_avaliacao', sa.String(), nullable=False),
    sa.Column('id_pedido', sa.String(), nullable=True),
    sa.Column('id_cliente', sa.String(), nullable=True),
    sa.Column('id_produto', sa.String(), nullable=True),
    sa.Column('nota_produto', sa.Float(), nullable=True),
    sa.Column('comentario_avaliacao', sa.Text(), nullable=True),
    sa.Column('nota_nps', sa.Float(), nullable=True),
    sa.Column('recomenda_produto', sa.Boolean(), nullable=True),
    sa.Column('data_avaliacao', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_avaliacao')
    )
    op.create_index(op.f('ix_fato_avaliacoes_id_avaliacao'), 'fato_avaliacoes', ['id_avaliacao'], unique=False)
    op.create_index(op.f('ix_fato_avaliacoes_id_cliente'), 'fato_avaliacoes', ['id_cliente'], unique=False)
    op.create_index(op.f('ix_fato_avaliacoes_id_pedido'), 'fato_avaliacoes', ['id_pedido'], unique=False)
    op.create_index(op.f('ix_fato_avaliacoes_id_produto'), 'fato_avaliacoes', ['id_produto'], unique=False)
    op.create_table('fato_clickstream',
    sa.Column('id_evento', sa.String(), nullable=False),
    sa.Column('id_sessao', sa.String(), nullable=True),
    sa.Column('id_cliente', sa.String(), nullable=True),
    sa.Column('id_dispositivo', sa.String(), nullable=True),
    sa.Column('id_produto', sa.String(), nullable=True),
    sa.Column('tipo_evento', sa.String(), nullable=True),
    sa.Column('canal_evento', sa.String(), nullable=True),
    sa.Column('dispositivo_evento', sa.String(), nullable=True),
    sa.Column('origem_sessao', sa.String(), nullable=True),
    sa.Column('data_evento', sa.String(), nullable=True),
    sa.Column('tempo_pagina_seg', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id_evento')
    )
    op.create_index(op.f('ix_fato_clickstream_id_cliente'), 'fato_clickstream', ['id_cliente'], unique=False)
    op.create_index(op.f('ix_fato_clickstream_id_dispositivo'), 'fato_clickstream', ['id_dispositivo'], unique=False)
    op.create_index(op.f('ix_fato_clickstream_id_evento'), 'fato_clickstream', ['id_evento'], unique=False)
    op.create_index(op.f('ix_fato_clickstream_id_produto'), 'fato_clickstream', ['id_produto'], unique=False)
    op.create_index(op.f('ix_fato_clickstream_id_sessao'), 'fato_clickstream', ['id_sessao'], unique=False)
    op.create_table('fato_suporte',
    sa.Column('ticket_id', sa.String(), nullable=False),
    sa.Column('id_cliente', sa.String(), nullable=True),
    sa.Column('id_pedido', sa.String(), nullable=True),
    sa.Column('tipo_problema', sa.String(), nullable=True),
    sa.Column('data_abertura', sa.String(), nullable=True),
    sa.Column('data_resolucao', sa.String(), nullable=True),
    sa.Column('tempo_resolucao_horas', sa.Float(), nullable=True),
    sa.Column('agente_suporte', sa.String(), nullable=True),
    sa.Column('nota_avaliacao_problema', sa.Float(), nullable=True),
    sa.Column('sentimento', sa.String(), nullable=True),
    sa.Column('status_ticket', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('ticket_id')
    )
    op.create_index(op.f('ix_fato_suporte_id_cliente'), 'fato_suporte', ['id_cliente'], unique=False)
    op.create_index(op.f('ix_fato_suporte_id_pedido'), 'fato_suporte', ['id_pedido'], unique=False)
    op.create_index(op.f('ix_fato_suporte_ticket_id'), 'fato_suporte', ['ticket_id'], unique=False)
    op.create_table('fato_vendas',
    sa.Column('id_pedido', sa.String(), nullable=False),
    sa.Column('id_cliente', sa.String(), nullable=True),
    sa.Column('id_produto', sa.String(), nullable=True),
    sa.Column('valor_pedido', sa.Float(), nullable=True),
    sa.Column('data_pedido', sa.String(), nullable=True),
    sa.Column('metodo_pagamento', sa.String(), nullable=True),
    sa.Column('status_pedido', sa.String(), nullable=True),
    sa.Column('quantidade_produto', sa.Integer(), nullable=True),
    sa.Column('data_prevista_entrega', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_pedido')
    )
    op.create_index(op.f('ix_fato_vendas_id_cliente'), 'fato_vendas', ['id_cliente'], unique=False)
    op.create_index(op.f('ix_fato_vendas_id_pedido'), 'fato_vendas', ['id_pedido'], unique=False)
    op.create_index(op.f('ix_fato_vendas_id_produto'), 'fato_vendas', ['id_produto'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fato_vendas_id_produto'), table_name='fato_vendas')
    op.drop_index(op.f('ix_fato_vendas_id_pedido'), table_name='fato_vendas')
    op.drop_index(op.f('ix_fato_vendas_id_cliente'), table_name='fato_vendas')
    op.drop_table('fato_vendas')
    op.drop_index(op.f('ix_fato_suporte_ticket_id'), table_name='fato_suporte')
    op.drop_index(op.f('ix_fato_suporte_id_pedido'), table_name='fato_suporte')
    op.drop_index(op.f('ix_fato_suporte_id_cliente'), table_name='fato_suporte')
    op.drop_table('fato_suporte')
    op.drop_index(op.f('ix_fato_clickstream_id_sessao'), table_name='fato_clickstream')
    op.drop_index(op.f('ix_fato_clickstream_id_produto'), table_name='fato_clickstream')
    op.drop_index(op.f('ix_fato_clickstream_id_evento'), table_name='fato_clickstream')
    op.drop_index(op.f('ix_fato_clickstream_id_dispositivo'), table_name='fato_clickstream')
    op.drop_index(op.f('ix_fato_clickstream_id_cliente'), table_name='fato_clickstream')
    op.drop_table('fato_clickstream')
    op.drop_index(op.f('ix_fato_avaliacoes_id_produto'), table_name='fato_avaliacoes')
    op.drop_index(op.f('ix_fato_avaliacoes_id_pedido'), table_name='fato_avaliacoes')
    op.drop_index(op.f('ix_fato_avaliacoes_id_cliente'), table_name='fato_avaliacoes')
    op.drop_index(op.f('ix_fato_avaliacoes_id_avaliacao'), table_name='fato_avaliacoes')
    op.drop_table('fato_avaliacoes')
    op.drop_index(op.f('ix_dim_produto_nome_produto'), table_name='dim_produto')
    op.drop_index(op.f('ix_dim_produto_id_produto'), table_name='dim_produto')
    op.drop_index(op.f('ix_dim_produto_categoria_produto'), table_name='dim_produto')
    op.drop_table('dim_produto')
    op.drop_index(op.f('ix_dim_cliente_dispositivo_id_dispositivo'), table_name='dim_cliente_dispositivo')
    op.drop_index(op.f('ix_dim_cliente_dispositivo_id_cliente'), table_name='dim_cliente_dispositivo')
    op.drop_table('dim_cliente_dispositivo')
    op.drop_index(op.f('ix_dim_cliente_sobrenome_cliente'), table_name='dim_cliente')
    op.drop_index(op.f('ix_dim_cliente_nome_cliente'), table_name='dim_cliente')
    op.drop_index(op.f('ix_dim_cliente_id_cliente'), table_name='dim_cliente')
    op.drop_index(op.f('ix_dim_cliente_email_cliente'), table_name='dim_cliente')
    op.drop_table('dim_cliente')
    # ### end Alembic commands ###
